{
    "name": "Kiiraaye Gouvernance",
    "version": "19.0.2.22.33",
    "category": "Organization",
    "summary": "Référentiel géographique et gestion des sections/coordinations Kiiraaye",
    "description": "Référentiel pays et subdivisions administratives, sections/coordinations, membres, bureaux, cartes membres, attributions de postes et contrôle d'accès hiérarchique.",
    "author": "Kiiraaye",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/kiiraaye_coordinator_rules.xml",
        "data/dashboard_data.xml",
        "data/sequence.xml",
        "data/position_data.xml",
        "data/organisation_type_data.xml",
        "data/effectif_status_data.xml",
        "views/geographie_views.xml",
        "views/partisan_views.xml",
        "views/partisan_governance_views.xml",
        "views/position_views.xml",
        "views/effectif_status_views.xml",
        "views/organisation_add_member_wizard_views.xml",
        "views/organisation_type_views.xml",
        "views/organisation_views.xml",
        "views/cadre_views.xml",
        "views/profession_views.xml",
        "views/cadre_assign_wizard_views.xml",
        "views/section_views.xml",
        "views/section_geography_config_views.xml",
        "views/section_coordinator_views.xml",
        "views/country_views.xml",
        "views/country_geography_config_views.xml",
        "views/country_geography_bulk_views.xml",
        "views/attribution_poste_views.xml",
        "views/report_member_card.xml",
        "views/report_member_card_modern.xml",
        "views/dashboard_views.xml",
        "views/demo_data_wizard_views.xml",
        "views/menus.xml"
    ],
    "assets": {
        "web.assets_backend": [
            "kiiraaye_governance/static/src/js/kiiraaye_dashboard.js",
            "kiiraaye_governance/static/src/css/kiiraaye_dashboard.css",
            "kiiraaye_governance/static/src/xml/kiiraaye_dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
    "post_init_hook": "post_init_hook"
}
