{
    "name": "Kiiraaye Gouvernance",
    "version": "19.0.2.15.0",
    "category": "Organization",
    "summary": "Référentiel géographique et gestion des sections/coordinations Kiiraaye",
    "description": "Référentiel pays et subdivisions administratives, sections/coordinations, membres, bureaux, cartes membres, attributions de postes et contrôle d'accès hiérarchique.",
    "author": "Kiiraaye",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/kiiraaye_coordinator_rules.xml",
        "data/sequence.xml",
        "data/position_data.xml",
        "views/geographie_views.xml",
        "views/partisan_views.xml",
        "views/partisan_governance_views.xml",
        "views/position_views.xml",
        "views/section_views.xml",
        "views/section_geography_config_views.xml",
        "views/section_coordinator_views.xml",
        "views/country_views.xml",
        "views/country_geography_config_views.xml",
        "views/country_geography_bulk_views.xml",
        "views/attribution_poste_views.xml",
        "views/report_member_card.xml",
        "views/report_member_card_modern.xml",
        "views/menus.xml"
    ],
    "installable": true,
    "application": true,
    "post_init_hook": "post_init_hook"
}
