{'name': 'Kiiraaye Gouvernance',
 'version': '19.0.5.0.0',
 'category': 'Operations',
 'summary': 'Gouvernance territoriale, dashboard OWL, cartographie et cartes '
            'de membre',
 'description': 'Plateforme de gouvernance territoriale et administrative pour '
                'Odoo 19 Community.',
 'author': 'Kiiraaye',
 'license': 'LGPL-3',
 'depends': ['base', 'mail', 'web'],
 'data': ['security/groups.xml',
          'security/ir.model.access.csv',
          'security/record_rules.xml',
          'data/sequences.xml',
          'data/positions.xml',
          'views/territoire_views.xml',
          'views/partisan_views.xml',
          'views/section_views.xml',
          'views/bureau_views.xml',
          'views/poste_views.xml',
          'views/document_views.xml',
          'views/reunion_views.xml',
          'views/formation_views.xml',
          'views/activity_views.xml',
          'views/plan_action_views.xml',
          'views/campagne_views.xml',
          'views/indicator_views.xml',
          'views/member_card_views.xml',
          'views/res_users_views.xml',
          'views/dashboard_action.xml',
          'views/menus.xml',
          'views/report_wizard.xml',
          'reports/report_paperformat.xml',
          'reports/member_card_report.xml',
          'reports/governance_report.xml'],
 'assets': {'web.assets_backend': ['kiiraaye_governance/static/src/js/territory_dashboard.js',
                                   'kiiraaye_governance/static/src/xml/territory_dashboard.xml',
                                   'kiiraaye_governance/static/src/scss/kiiraaye.scss']},
 'installable': True,
 'application': True}