from . import property
from . import assignment
from . import contract
from . import tenant
from . import inspection
from . import res_partner
from . import dashboard
from . import address
from . import property_type
from . import product_integration
