from . import effectif_status
from . import geographie
from . import country_geography
from . import country_geography_validation
from . import geography_mapping
from . import senegal_geography_source
from . import section
from . import section_geography_config
from . import senegal_geography
from . import organisation_type
from . import organisation
from . import organisation_add_member_wizard
from . import partisan
from . import profession
from . import cadre
from . import cadre_assign_wizard
from . import partisan_governance
from . import partisan_governance_superuser
from . import position
from . import attribution_poste
from . import section_coordinator
from . import user_scope
from . import dashboard
from . import demo_data_wizard
from . import ralliement
from . import ralliement_add_member_wizard
from . import resend_mail
